/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { YouError } from "./youerror.js";

/**
 * The message returned by the error
 */
export type AgentRuns401ResponseErrorData = {
  detail?: string | undefined;
};

/**
 * The message returned by the error
 */
export class AgentRuns401ResponseError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: AgentRuns401ResponseErrorData;

  constructor(
    err: AgentRuns401ResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "AgentRuns401ResponseError";
  }
}

/** @internal */
export const AgentRuns401ResponseError$inboundSchema: z.ZodMiniType<
  AgentRuns401ResponseError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new AgentRuns401ResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
