/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { YouError } from "./youerror.js";

export type AgentRuns422ResponseErrorData = {
  detail?: Array<models.Detail> | undefined;
};

export class AgentRuns422ResponseError extends YouError {
  detail?: Array<models.Detail> | undefined;

  /** The original data that was passed to this error instance. */
  data$: AgentRuns422ResponseErrorData;

  constructor(
    err: AgentRuns422ResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "AgentRuns422ResponseError";
  }
}

/** @internal */
export const AgentRuns422ResponseError$inboundSchema: z.ZodMiniType<
  AgentRuns422ResponseError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(z.array(z.lazy(() => models.Detail$inboundSchema))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new AgentRuns422ResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
