/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { YouError } from "./youerror.js";

/**
 * Internal Server Error
 */
export type ContentsInternalServerErrorData = {
  detail?: string | undefined;
};

/**
 * Internal Server Error
 */
export class ContentsInternalServerError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ContentsInternalServerErrorData;

  constructor(
    err: ContentsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ContentsInternalServerError";
  }
}

/**
 * Forbidden
 */
export type ContentsForbiddenErrorData = {
  detail?: string | undefined;
};

/**
 * Forbidden
 */
export class ContentsForbiddenError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ContentsForbiddenErrorData;

  constructor(
    err: ContentsForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ContentsForbiddenError";
  }
}

/**
 * Unauthorized
 */
export type ContentsUnauthorizedErrorData = {
  /**
   * Error detail message.
   */
  detail?: string | undefined;
};

/**
 * Unauthorized
 */
export class ContentsUnauthorizedError extends YouError {
  /**
   * Error detail message.
   */
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ContentsUnauthorizedErrorData;

  constructor(
    err: ContentsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ContentsUnauthorizedError";
  }
}

/** @internal */
export const ContentsInternalServerError$inboundSchema: z.ZodMiniType<
  ContentsInternalServerError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ContentsInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ContentsForbiddenError$inboundSchema: z.ZodMiniType<
  ContentsForbiddenError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ContentsForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ContentsUnauthorizedError$inboundSchema: z.ZodMiniType<
  ContentsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ContentsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
