/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { YouError } from "./youerror.js";

/**
 * Internal Server Error during authentication/authorization middleware.
 */
export type ResearchInternalServerErrorData = {
  detail?: string | undefined;
};

/**
 * Internal Server Error during authentication/authorization middleware.
 */
export class ResearchInternalServerError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ResearchInternalServerErrorData;

  constructor(
    err: ResearchInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ResearchInternalServerError";
  }
}

/**
 * Unprocessable Entity. Request validation failed.
 */
export type UnprocessableEntityErrorData = {
  detail?: Array<operations.Detail> | undefined;
};

/**
 * Unprocessable Entity. Request validation failed.
 */
export class UnprocessableEntityError extends YouError {
  detail?: Array<operations.Detail> | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnprocessableEntityErrorData;

  constructor(
    err: UnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "UnprocessableEntityError";
  }
}

/**
 * Forbidden. API key lacks scope for this path.
 */
export type ResearchForbiddenErrorData = {
  detail?: string | undefined;
};

/**
 * Forbidden. API key lacks scope for this path.
 */
export class ResearchForbiddenError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ResearchForbiddenErrorData;

  constructor(
    err: ResearchForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ResearchForbiddenError";
  }
}

/**
 * Unauthorized. Problems with API key.
 */
export type ResearchUnauthorizedErrorData = {
  /**
   * Error detail message.
   */
  detail?: string | undefined;
};

/**
 * Unauthorized. Problems with API key.
 */
export class ResearchUnauthorizedError extends YouError {
  /**
   * Error detail message.
   */
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ResearchUnauthorizedErrorData;

  constructor(
    err: ResearchUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "ResearchUnauthorizedError";
  }
}

/** @internal */
export const ResearchInternalServerError$inboundSchema: z.ZodMiniType<
  ResearchInternalServerError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ResearchInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnprocessableEntityError$inboundSchema: z.ZodMiniType<
  UnprocessableEntityError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(
      z.array(z.lazy(() => operations.Detail$inboundSchema)),
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ResearchForbiddenError$inboundSchema: z.ZodMiniType<
  ResearchForbiddenError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ResearchForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ResearchUnauthorizedError$inboundSchema: z.ZodMiniType<
  ResearchUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ResearchUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
