/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { YouError } from "./youerror.js";

/**
 * Internal Server Error during authentication/authorization middleware.
 */
export type SearchInternalServerErrorData = {
  detail?: string | undefined;
};

/**
 * Internal Server Error during authentication/authorization middleware.
 */
export class SearchInternalServerError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchInternalServerErrorData;

  constructor(
    err: SearchInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "SearchInternalServerError";
  }
}

/**
 * Forbidden. API key lacks scope for this path.
 */
export type SearchForbiddenErrorData = {
  detail?: string | undefined;
};

/**
 * Forbidden. API key lacks scope for this path.
 */
export class SearchForbiddenError extends YouError {
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchForbiddenErrorData;

  constructor(
    err: SearchForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "SearchForbiddenError";
  }
}

/**
 * Unauthorized. Problems with API key.
 */
export type SearchUnauthorizedErrorData = {
  /**
   * Error detail message.
   */
  detail?: string | undefined;
};

/**
 * Unauthorized. Problems with API key.
 */
export class SearchUnauthorizedError extends YouError {
  /**
   * Error detail message.
   */
  detail?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchUnauthorizedErrorData;

  constructor(
    err: SearchUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.detail != null) this.detail = err.detail;

    this.name = "SearchUnauthorizedError";
  }
}

/** @internal */
export const SearchInternalServerError$inboundSchema: z.ZodMiniType<
  SearchInternalServerError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchForbiddenError$inboundSchema: z.ZodMiniType<
  SearchForbiddenError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchUnauthorizedError$inboundSchema: z.ZodMiniType<
  SearchUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    detail: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
