/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsRuns } from "../funcs/agentsRuns.js";
import { contents } from "../funcs/contents.js";
import { research } from "../funcs/research.js";
import { search } from "../funcs/search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class You extends ClientSDK {
  /**
   * Run an Agent
   *
   * @remarks
   * Execute queries using You.com's AI agents. This endpoint supports three agent types:
   *
   * - **Express Agent**: Fast responses with optional web search (max 1 search)
   * - **Advanced Agent**: Complex queries with multi-turn reasoning, planning, and tool usage
   * - **Custom Agent**: User-configured assistants created in the You.com UI
   *
   * The response format depends on the `stream` parameter - either a complete JSON payload or Server-Sent Events (SSE).
   */
  async agentsRuns(
    request: operations.AgentsRunsRequest,
    options?: RequestOptions,
  ): Promise<operations.AgentsRunsResponse> {
    return unwrapAsync(agentsRuns(
      this,
      request,
      options,
    ));
  }

  /**
   * Returns a list of unified search results from web and news sources
   *
   * @remarks
   * This endpoint is designed to return LLM-ready web results based on a user's query. Based on a classification mechanism, it can return web results and news associated with your query. If you need to feed an LLM with the results of a query that sounds like `What are the latest geopolitical updates from India`, then this endpoint is the right one for you.
   */
  async search(
    request: operations.SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchResponse> {
    return unwrapAsync(search(
      this,
      request,
      options,
    ));
  }

  /**
   * Returns the content of the web pages
   *
   * @remarks
   * Returns the HTML or Markdown of a target webpage.
   */
  async contents(
    request: operations.ContentsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.ContentsResponse>> {
    return unwrapAsync(contents(
      this,
      request,
      options,
    ));
  }

  /**
   * Returns comprehensive research-grade answers with multi-step reasoning
   *
   * @remarks
   * Research goes beyond a single web search. In response to your question, it runs multiple searches, reads through the sources, and synthesizes everything into a thorough, well-cited answer. Use it when a question is too complex for a simple lookup, and when you need a response you can actually trust and verify.
   */
  async research(
    request: operations.ResearchRequest,
    options?: RequestOptions,
  ): Promise<operations.ResearchResponse> {
    return unwrapAsync(research(
      this,
      request,
      options,
    ));
  }
}
