/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsRuns } from "../funcs/agentsRuns.js";
import { contents } from "../funcs/contents.js";
import { search } from "../funcs/search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class You extends ClientSDK {
  /**
   * Run an Agent
   *
   * @remarks
   * Execute queries using You.com's AI agents. This endpoint supports three agent types:
   *
   * - **Express Agent**: Fast responses with optional web search (max 1 search)
   * - **Advanced Agent**: Complex queries with multi-turn reasoning, planning, and tool usage
   * - **Custom Agent**: User-configured assistants created in the You.com UI
   *
   * The response format depends on the `stream` parameter - either a complete JSON payload or Server-Sent Events (SSE).
   */
  async agentsRuns(
    request: operations.AgentsRunsRequest,
    options?: RequestOptions,
  ): Promise<operations.AgentsRunsResponse> {
    return unwrapAsync(agentsRuns(
      this,
      request,
      options,
    ));
  }

  /**
   * Returns a list of unified search results from web and news sources
   */
  async search(
    request: operations.SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchResponse> {
    return unwrapAsync(search(
      this,
      request,
      options,
    ));
  }

  /**
   * Returns the content of the web pages
   */
  async contents(
    request: operations.ContentsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.ContentsResponse>> {
    return unwrapAsync(contents(
      this,
      request,
      options,
    ));
  }
}
