/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { type Unrecognized, unrecognized } from "./unrecognized.js";

let globalCount = 0;
let refCount = 0;

export function defaultToZeroValue<T>(value: T): Unrecognized<T> {
  globalCount++;
  return unrecognized(value);
}

export function startCountingDefaultToZeroValue() {
  refCount++;
  const start = globalCount;
  return {
    end: () => {
      const count = globalCount - start;
      if (--refCount === 0) globalCount = 0;
      return count;
    },
  };
}
