/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @youdotcom-oss/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx agentsRuns.example.ts
 */

import { You } from "@youdotcom-oss/sdk";

const you = new You({
  apiKeyAuth: process.env["YOU_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await you.agentsRuns({
    agent: "express",
    input: "What is the capital of France?",
    stream: false,
  });

  console.log(result);
}

main().catch(console.error);
