workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    You.com SDK:
        inputs:
            - location: ./openapi_schemas/openapi_unified_agents.yaml
            - location: ./openapi_schemas/openapi_search_v1.yaml
            - location: ./openapi_schemas/openapi_contents.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/youcom/documentation/you-com-sdk
targets:
    you:
        target: typescript
        source: You.com SDK
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/youcom/documentation/you-com-sdk-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
