/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { EventStream } from "../../lib/event-streams.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const AgentsRunsServerList = [
  "https://api.you.com",
] as const;

/**
 * The parameters to ask the agent a question
 */
export type AgentsRunsRequest =
  | models.ExpressAgentRunsRequest
  | models.AdvancedAgentRunsRequest
  | models.CustomAgentRunsRequest;

export type AgentsRunsResponse =
  | models.AgentRunsBatchResponse
  | EventStream<models.AgentRunsStreamingResponse>;

/** @internal */
export type AgentsRunsRequest$Outbound =
  | models.ExpressAgentRunsRequest$Outbound
  | models.AdvancedAgentRunsRequest$Outbound
  | models.CustomAgentRunsRequest$Outbound;

/** @internal */
export const AgentsRunsRequest$outboundSchema: z.ZodMiniType<
  AgentsRunsRequest$Outbound,
  AgentsRunsRequest
> = smartUnion([
  models.ExpressAgentRunsRequest$outboundSchema,
  models.AdvancedAgentRunsRequest$outboundSchema,
  models.CustomAgentRunsRequest$outboundSchema,
]);

export function agentsRunsRequestToJSON(
  agentsRunsRequest: AgentsRunsRequest,
): string {
  return JSON.stringify(
    AgentsRunsRequest$outboundSchema.parse(agentsRunsRequest),
  );
}

/** @internal */
export const AgentsRunsResponse$inboundSchema: z.ZodMiniType<
  AgentsRunsResponse,
  unknown
> = smartUnion([
  models.AgentRunsBatchResponse$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        return {
          value: models.AgentRunsStreamingResponse$inboundSchema.parse(
            rawEvent,
          ),
        };
      });
    }),
  ),
]);

export function agentsRunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentsRunsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentsRunsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentsRunsResponse' from JSON`,
  );
}
