/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ContentsRequest = {
  /**
   * Array of URLs to fetch the contents from.
   */
  urls?: Array<string> | undefined;
  /**
   * The formats of the content to be returned. Can include 'html', 'markdown', and/or 'metadata'.
   */
  formats?: Array<models.ContentsFormats> | undefined;
  /**
   * The timeout in seconds for crawling each URL. Must be between 1 and 60 seconds.
   */
  crawlTimeout?: number | undefined;
};

export type ContentsResponse = {
  /**
   * The webpage URL whose content has been fetched.
   */
  url?: string | undefined;
  /**
   * The title of the web page.
   */
  title?: string | undefined;
  /**
   * The retrieved HTML content of the web page.
   */
  html?: string | null | undefined;
  /**
   * The retrieved Markdown content of the web page.
   */
  markdown?: string | null | undefined;
  /**
   * Metadata about the web page. Only returned when 'metadata' is included in the formats array.
   */
  metadata?: models.ContentsMetadata | null | undefined;
};

/** @internal */
export type ContentsRequest$Outbound = {
  urls?: Array<string> | undefined;
  formats?: Array<string> | undefined;
  crawl_timeout?: number | undefined;
};

/** @internal */
export const ContentsRequest$outboundSchema: z.ZodMiniType<
  ContentsRequest$Outbound,
  ContentsRequest
> = z.pipe(
  z.object({
    urls: z.optional(z.array(z.string())),
    formats: z.optional(z.array(models.ContentsFormats$outboundSchema)),
    crawlTimeout: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      crawlTimeout: "crawl_timeout",
    });
  }),
);

export function contentsRequestToJSON(
  contentsRequest: ContentsRequest,
): string {
  return JSON.stringify(ContentsRequest$outboundSchema.parse(contentsRequest));
}

/** @internal */
export const ContentsResponse$inboundSchema: z.ZodMiniType<
  ContentsResponse,
  unknown
> = z.object({
  url: types.optional(types.string()),
  title: types.optional(types.string()),
  html: z.optional(z.nullable(types.string())),
  markdown: z.optional(z.nullable(types.string())),
  metadata: z.optional(z.nullable(models.ContentsMetadata$inboundSchema)),
});

export function contentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentsResponse' from JSON`,
  );
}
