/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FormatEnum2 = {
  Html: "html",
  Markdown: "markdown",
} as const;
export type FormatEnum2 = ClosedEnum<typeof FormatEnum2>;

/**
 * The format of the content to be returned.
 */
export const FormatEnum1 = {
  Html: "html",
  Markdown: "markdown",
} as const;
/**
 * The format of the content to be returned.
 */
export type FormatEnum1 = ClosedEnum<typeof FormatEnum1>;

/**
 * The format of the content to be returned.
 */
export type Format = FormatEnum1 | FormatEnum2;

export type ContentsRequest = {
  /**
   * Array of URLs to fetch the contents from.
   */
  urls?: Array<string> | undefined;
  /**
   * The format of the content to be returned.
   */
  format?: FormatEnum1 | FormatEnum2 | undefined;
};

export type ContentsMetadata = {
  /**
   * The OpenGraph site name of the web page.
   */
  siteName?: string | undefined;
  /**
   * The URL of the favicon of the web page's domain.
   */
  faviconUrl?: string | undefined;
};

export type ContentsResponse = {
  /**
   * The webpage URL whose content has been fetched.
   */
  url?: string | undefined;
  /**
   * The title of the web page.
   */
  title?: string | undefined;
  /**
   * The retrieved HTML content of the web page.
   */
  html?: string | null | undefined;
  /**
   * The retrieved Markdown content of the web page.
   */
  markdown?: string | null | undefined;
  metadata?: ContentsMetadata | undefined;
};

/** @internal */
export const FormatEnum2$outboundSchema: z.ZodMiniEnum<typeof FormatEnum2> = z
  .enum(FormatEnum2);

/** @internal */
export const FormatEnum1$outboundSchema: z.ZodMiniEnum<typeof FormatEnum1> = z
  .enum(FormatEnum1);

/** @internal */
export type Format$Outbound = string | string;

/** @internal */
export const Format$outboundSchema: z.ZodMiniType<Format$Outbound, Format> =
  smartUnion([FormatEnum1$outboundSchema, FormatEnum2$outboundSchema]);

export function formatToJSON(format: Format): string {
  return JSON.stringify(Format$outboundSchema.parse(format));
}

/** @internal */
export type ContentsRequest$Outbound = {
  urls?: Array<string> | undefined;
  format?: string | string | undefined;
};

/** @internal */
export const ContentsRequest$outboundSchema: z.ZodMiniType<
  ContentsRequest$Outbound,
  ContentsRequest
> = z.object({
  urls: z.optional(z.array(z.string())),
  format: z.optional(
    smartUnion([FormatEnum1$outboundSchema, FormatEnum2$outboundSchema]),
  ),
});

export function contentsRequestToJSON(
  contentsRequest: ContentsRequest,
): string {
  return JSON.stringify(ContentsRequest$outboundSchema.parse(contentsRequest));
}

/** @internal */
export const ContentsMetadata$inboundSchema: z.ZodMiniType<
  ContentsMetadata,
  unknown
> = z.pipe(
  z.object({
    site_name: types.optional(types.string()),
    favicon_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "site_name": "siteName",
      "favicon_url": "faviconUrl",
    });
  }),
);

export function contentsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<ContentsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentsMetadata' from JSON`,
  );
}

/** @internal */
export const ContentsResponse$inboundSchema: z.ZodMiniType<
  ContentsResponse,
  unknown
> = z.object({
  url: types.optional(types.string()),
  title: types.optional(types.string()),
  html: z.optional(z.nullable(types.string())),
  markdown: z.optional(z.nullable(types.string())),
  metadata: types.optional(z.lazy(() => ContentsMetadata$inboundSchema)),
});

export function contentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentsResponse' from JSON`,
  );
}
