/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.
 *
 * @remarks
 *
 * Available levels:
 * - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
 * - `standard`: The default. Balances speed and depth, a good fit for most questions.
 * - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
 * - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
 */
export const ResearchEffort = {
  Lite: "lite",
  Standard: "standard",
  Deep: "deep",
  Exhaustive: "exhaustive",
} as const;
/**
 * Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.
 *
 * @remarks
 *
 * Available levels:
 * - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
 * - `standard`: The default. Balances speed and depth, a good fit for most questions.
 * - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
 * - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
 */
export type ResearchEffort = ClosedEnum<typeof ResearchEffort>;

export type ResearchRequest = {
  /**
   * The research question or complex query requiring in-depth investigation and multi-step reasoning.
   *
   * @remarks
   *
   * Note: The maximum length of the input is 40,000 characters.
   */
  input: string;
  /**
   * Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.
   *
   * @remarks
   *
   * Available levels:
   * - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
   * - `standard`: The default. Balances speed and depth, a good fit for most questions.
   * - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
   * - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
   */
  researchEffort?: ResearchEffort | undefined;
};

export type Loc = string | number;

export type Input = {};

/**
 * The input value that caused the error.
 */
export type InputUnion = string | Input;

export type Detail = {
  /**
   * The validation error type.
   */
  type: string;
  /**
   * The location of the error as a path of segments (strings for field names, integers for byte offsets).
   */
  loc: Array<string | number>;
  /**
   * A human-readable description of the error.
   */
  msg: string;
  /**
   * The input value that caused the error.
   */
  input: string | Input;
  /**
   * Additional context about the error.
   */
  ctx?: { [k: string]: any } | undefined;
};

/**
 * The format of the content field.
 */
export const ContentType = {
  Text: "text",
} as const;
/**
 * The format of the content field.
 */
export type ContentType = ClosedEnum<typeof ContentType>;

export type Source = {
  /**
   * The URL of the source webpage.
   */
  url: string;
  /**
   * The title of the source webpage.
   */
  title?: string | undefined;
  /**
   * Relevant excerpts from the source page that were used in generating the answer.
   */
  snippets?: Array<string> | undefined;
};

/**
 * The research output containing the answer and sources.
 */
export type Output = {
  /**
   * The comprehensive response with inline citations. The content is formatted in Markdown and includes numbered citations that reference the items in the sources array.
   */
  content: string;
  /**
   * The format of the content field.
   */
  contentType: ContentType;
  /**
   * A list of web sources used to generate the answer.
   */
  sources: Array<Source>;
};

/**
 * A JSON object containing a comprehensive answer with citations and supporting search results
 */
export type ResearchResponse = {
  /**
   * The research output containing the answer and sources.
   */
  output: Output;
};

/** @internal */
export const ResearchEffort$outboundSchema: z.ZodMiniEnum<
  typeof ResearchEffort
> = z.enum(ResearchEffort);

/** @internal */
export type ResearchRequest$Outbound = {
  input: string;
  research_effort: string;
};

/** @internal */
export const ResearchRequest$outboundSchema: z.ZodMiniType<
  ResearchRequest$Outbound,
  ResearchRequest
> = z.pipe(
  z.object({
    input: z.string(),
    researchEffort: z._default(ResearchEffort$outboundSchema, "standard"),
  }),
  z.transform((v) => {
    return remap$(v, {
      researchEffort: "research_effort",
    });
  }),
);

export function researchRequestToJSON(
  researchRequest: ResearchRequest,
): string {
  return JSON.stringify(ResearchRequest$outboundSchema.parse(researchRequest));
}

/** @internal */
export const Loc$inboundSchema: z.ZodMiniType<Loc, unknown> = smartUnion([
  types.string(),
  types.number(),
]);

export function locFromJSON(
  jsonString: string,
): SafeParseResult<Loc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Loc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Loc' from JSON`,
  );
}

/** @internal */
export const Input$inboundSchema: z.ZodMiniType<Input, unknown> = z.object({});

export function inputFromJSON(
  jsonString: string,
): SafeParseResult<Input, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Input$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Input' from JSON`,
  );
}

/** @internal */
export const InputUnion$inboundSchema: z.ZodMiniType<InputUnion, unknown> =
  smartUnion([types.string(), z.lazy(() => Input$inboundSchema)]);

export function inputUnionFromJSON(
  jsonString: string,
): SafeParseResult<InputUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputUnion' from JSON`,
  );
}

/** @internal */
export const Detail$inboundSchema: z.ZodMiniType<Detail, unknown> = z.object({
  type: types.string(),
  loc: z.array(smartUnion([types.string(), types.number()])),
  msg: types.string(),
  input: smartUnion([types.string(), z.lazy(() => Input$inboundSchema)]),
  ctx: types.optional(z.record(z.string(), z.any())),
});

export function detailFromJSON(
  jsonString: string,
): SafeParseResult<Detail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Detail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Detail' from JSON`,
  );
}

/** @internal */
export const ContentType$inboundSchema: z.ZodMiniEnum<typeof ContentType> = z
  .enum(ContentType);

/** @internal */
export const Source$inboundSchema: z.ZodMiniType<Source, unknown> = z.object({
  url: types.string(),
  title: types.optional(types.string()),
  snippets: types.optional(z.array(types.string())),
});

export function sourceFromJSON(
  jsonString: string,
): SafeParseResult<Source, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Source$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Source' from JSON`,
  );
}

/** @internal */
export const Output$inboundSchema: z.ZodMiniType<Output, unknown> = z.pipe(
  z.object({
    content: types.string(),
    content_type: ContentType$inboundSchema,
    sources: z.array(z.lazy(() => Source$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "content_type": "contentType",
    });
  }),
);

export function outputFromJSON(
  jsonString: string,
): SafeParseResult<Output, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Output$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Output' from JSON`,
  );
}

/** @internal */
export const ResearchResponse$inboundSchema: z.ZodMiniType<
  ResearchResponse,
  unknown
> = z.object({
  output: z.lazy(() => Output$inboundSchema),
});

export function researchResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResearchResponse' from JSON`,
  );
}
