/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ComputeTool,
  ComputeTool$Outbound,
  ComputeTool$outboundSchema,
} from "./computetool.js";
import {
  ResearchTool,
  ResearchTool$Outbound,
  ResearchTool$outboundSchema,
} from "./researchtool.js";
import { Verbosity, Verbosity$outboundSchema } from "./verbosity.js";

/**
 * Setting this value to "advanced" is mandatory to use the advanced agent.
 */
export const AdvancedAgentRunsRequestAgent = {
  Advanced: "advanced",
} as const;
/**
 * Setting this value to "advanced" is mandatory to use the advanced agent.
 */
export type AdvancedAgentRunsRequestAgent = ClosedEnum<
  typeof AdvancedAgentRunsRequestAgent
>;

export type Tool =
  | (ResearchTool & { type: "research" })
  | (ComputeTool & { type: "compute" });

/**
 * Defines the maximum number of steps the agent uses in its workflow plan to answer your query. Higher values allow for more tool calls, but it takes longer for the agent to provide the response. For instance, setting max_workflow_steps=5 could allow the agent to call the research tool 3 times and the compute tool 2 times.
 */
export type WorkflowConfig = {
  maxWorkflowSteps?: number | undefined;
};

export type AdvancedAgentRunsRequest = {
  /**
   * Setting this value to "advanced" is mandatory to use the advanced agent.
   */
  agent: AdvancedAgentRunsRequestAgent;
  /**
   * The question you'd like to ask the agent
   */
  input: string;
  /**
   * Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished.
   */
  stream?: boolean | undefined;
  /**
   * The advanced agent accepts either `compute` or `research` tools <Note> Compute allows your agent to use a Python code interpreter for tasks such as data analysis, mathematical calculations, and plot generation.<br><br>   Research iteratively searches the web, analyzes the results, and stops when finished. It then provides a comprehensive report to your agent with current, cited information.</Note>
   */
  tools?:
    | Array<
      | (ResearchTool & { type: "research" })
      | (ComputeTool & { type: "compute" })
    >
    | undefined;
  /**
   * Controls the level of detail provided by the agent's response. Choosing high maps to a long-form report while medium maps to a medium verbosity report that captures most details but is less comprehensive.
   */
  verbosity?: Verbosity | undefined;
  /**
   * Defines the maximum number of steps the agent uses in its workflow plan to answer your query. Higher values allow for more tool calls, but it takes longer for the agent to provide the response. For instance, setting max_workflow_steps=5 could allow the agent to call the research tool 3 times and the compute tool 2 times.
   */
  workflowConfig?: WorkflowConfig | undefined;
};

/** @internal */
export const AdvancedAgentRunsRequestAgent$outboundSchema: z.ZodMiniEnum<
  typeof AdvancedAgentRunsRequestAgent
> = z.enum(AdvancedAgentRunsRequestAgent);

/** @internal */
export type Tool$Outbound =
  | (ResearchTool$Outbound & { type: "research" })
  | (ComputeTool$Outbound & { type: "compute" });

/** @internal */
export const Tool$outboundSchema: z.ZodMiniType<Tool$Outbound, Tool> = z.union([
  z.intersection(
    ResearchTool$outboundSchema,
    z.object({ type: z.literal("research") }),
  ),
  z.intersection(
    ComputeTool$outboundSchema,
    z.object({ type: z.literal("compute") }),
  ),
]);

export function toolToJSON(tool: Tool): string {
  return JSON.stringify(Tool$outboundSchema.parse(tool));
}

/** @internal */
export type WorkflowConfig$Outbound = {
  max_workflow_steps: number;
};

/** @internal */
export const WorkflowConfig$outboundSchema: z.ZodMiniType<
  WorkflowConfig$Outbound,
  WorkflowConfig
> = z.pipe(
  z.object({
    maxWorkflowSteps: z._default(z.int(), 10),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxWorkflowSteps: "max_workflow_steps",
    });
  }),
);

export function workflowConfigToJSON(workflowConfig: WorkflowConfig): string {
  return JSON.stringify(WorkflowConfig$outboundSchema.parse(workflowConfig));
}

/** @internal */
export type AdvancedAgentRunsRequest$Outbound = {
  agent: string;
  input: string;
  stream: boolean;
  tools?:
    | Array<
      | (ResearchTool$Outbound & { type: "research" })
      | (ComputeTool$Outbound & { type: "compute" })
    >
    | undefined;
  verbosity?: string | undefined;
  workflow_config?: WorkflowConfig$Outbound | undefined;
};

/** @internal */
export const AdvancedAgentRunsRequest$outboundSchema: z.ZodMiniType<
  AdvancedAgentRunsRequest$Outbound,
  AdvancedAgentRunsRequest
> = z.pipe(
  z.object({
    agent: AdvancedAgentRunsRequestAgent$outboundSchema,
    input: z.string(),
    stream: z._default(z.boolean(), false),
    tools: z.optional(
      z.array(
        z.union([
          z.intersection(
            ResearchTool$outboundSchema,
            z.object({ type: z.literal("research") }),
          ),
          z.intersection(
            ComputeTool$outboundSchema,
            z.object({ type: z.literal("compute") }),
          ),
        ]),
      ),
    ),
    verbosity: z.optional(Verbosity$outboundSchema),
    workflowConfig: z.optional(z.lazy(() => WorkflowConfig$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      workflowConfig: "workflow_config",
    });
  }),
);

export function advancedAgentRunsRequestToJSON(
  advancedAgentRunsRequest: AdvancedAgentRunsRequest,
): string {
  return JSON.stringify(
    AdvancedAgentRunsRequest$outboundSchema.parse(advancedAgentRunsRequest),
  );
}
