/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentRunsResponseWebSearchResult,
  AgentRunsResponseWebSearchResult$inboundSchema,
} from "./agentrunsresponsewebsearchresult.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The type of output. This can either be:
 *
 * @remarks
 * * `message.answer` for text responses
 * * `web_search.results` for output that contains web links. `web_search.results` only appear when you use the `research` tool or express agent with web_search
 */
export const Type = {
  MessageAnswer: "message.answer",
  WebSearchResults: "web_search.results",
} as const;
/**
 * The type of output. This can either be:
 *
 * @remarks
 * * `message.answer` for text responses
 * * `web_search.results` for output that contains web links. `web_search.results` only appear when you use the `research` tool or express agent with web_search
 */
export type Type = OpenEnum<typeof Type>;

/**
 * The response populated by the agent.
 */
export type AgentRunsResponseOutput = {
  /**
   * The text response of the agent. This field returns when `type == message.answer`. The response returns as markdown formatted text.
   *
   * @remarks
   *
   * For an overview of Markdown syntax, see the [Basic Syntax Markdown Guide](https://www.markdownguide.org/basic-syntax/)
   */
  text?: string | undefined;
  /**
   * The type of output. This can either be:
   *
   * @remarks
   * * `message.answer` for text responses
   * * `web_search.results` for output that contains web links. `web_search.results` only appear when you use the `research` tool or express agent with web_search
   */
  type: Type;
  /**
   * The text response of the agent.
   *
   * @remarks
   * This field returns when `type == web_search.results`
   */
  content?: Array<AgentRunsResponseWebSearchResult> | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const AgentRunsResponseOutput$inboundSchema: z.ZodMiniType<
  AgentRunsResponseOutput,
  unknown
> = z.object({
  text: types.optional(types.string()),
  type: Type$inboundSchema,
  content: types.optional(
    z.array(AgentRunsResponseWebSearchResult$inboundSchema),
  ),
});

export function agentRunsResponseOutputFromJSON(
  jsonString: string,
): SafeParseResult<AgentRunsResponseOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRunsResponseOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRunsResponseOutput' from JSON`,
  );
}
