/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The text response of the agent. This field only returns when the type is `web_search.results`
 */
export type AgentRunsResponseWebSearchResult = {
  /**
   * The type of content the agent can return outside a text response
   */
  sourceType: "web_search";
  /**
   * The web search result the agent returned along in its response
   */
  citationUri: string;
  /**
   * This is currently unused
   */
  provider?: string | undefined;
  /**
   * The title of the web site returned under url
   */
  title: string;
  /**
   * A textual portion of the web site returned under url
   */
  snippet: string;
  /**
   * The thumbnail image of the url
   */
  thumbnailUrl?: string | undefined;
  /**
   * The web search result the agent returned along in its response
   */
  url: string;
};

/** @internal */
export const AgentRunsResponseWebSearchResult$inboundSchema: z.ZodMiniType<
  AgentRunsResponseWebSearchResult,
  unknown
> = z.pipe(
  z.object({
    source_type: types.literal("web_search"),
    citation_uri: types.string(),
    provider: types.optional(types.string()),
    title: types.string(),
    snippet: types.string(),
    thumbnail_url: types.optional(types.string()),
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_type": "sourceType",
      "citation_uri": "citationUri",
      "thumbnail_url": "thumbnailUrl",
    });
  }),
);

export function agentRunsResponseWebSearchResultFromJSON(
  jsonString: string,
): SafeParseResult<AgentRunsResponseWebSearchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRunsResponseWebSearchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRunsResponseWebSearchResult' from JSON`,
  );
}
