/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ResponseCreated,
  ResponseCreated$inboundSchema,
} from "./responsecreated.js";
import { ResponseDone, ResponseDone$inboundSchema } from "./responsedone.js";
import {
  ResponseOutputContentFull,
  ResponseOutputContentFull$inboundSchema,
} from "./responseoutputcontentfull.js";
import {
  ResponseOutputItemAdded,
  ResponseOutputItemAdded$inboundSchema,
} from "./responseoutputitemadded.js";
import {
  ResponseOutputItemDone,
  ResponseOutputItemDone$inboundSchema,
} from "./responseoutputitemdone.js";
import {
  ResponseOutputTextDelta,
  ResponseOutputTextDelta$inboundSchema,
} from "./responseoutputtextdelta.js";
import {
  ResponseStarting,
  ResponseStarting$inboundSchema,
} from "./responsestarting.js";

export type Data =
  | ResponseCreated
  | ResponseStarting
  | ResponseOutputItemAdded
  | ResponseOutputContentFull
  | ResponseOutputItemDone
  | ResponseOutputTextDelta
  | ResponseDone;

/**
 * A server-sent event containing stock market update content
 */
export type AgentRunsStreamingResponse = {
  /**
   * Sequence number of the SSE event, starts from 0
   */
  id: string;
  /**
   * The type of the SSE event
   */
  event: string;
  data:
    | ResponseCreated
    | ResponseStarting
    | ResponseOutputItemAdded
    | ResponseOutputContentFull
    | ResponseOutputItemDone
    | ResponseOutputTextDelta
    | ResponseDone;
};

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.union([
  ResponseCreated$inboundSchema,
  ResponseStarting$inboundSchema,
  ResponseOutputItemAdded$inboundSchema,
  ResponseOutputContentFull$inboundSchema,
  ResponseOutputItemDone$inboundSchema,
  ResponseOutputTextDelta$inboundSchema,
  ResponseDone$inboundSchema,
]);

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const AgentRunsStreamingResponse$inboundSchema: z.ZodMiniType<
  AgentRunsStreamingResponse,
  unknown
> = z.object({
  id: types.string(),
  event: types.string(),
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    z.union([
      ResponseCreated$inboundSchema,
      ResponseStarting$inboundSchema,
      ResponseOutputItemAdded$inboundSchema,
      ResponseOutputContentFull$inboundSchema,
      ResponseOutputItemDone$inboundSchema,
      ResponseOutputTextDelta$inboundSchema,
      ResponseDone$inboundSchema,
    ]),
  ),
});

export function agentRunsStreamingResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentRunsStreamingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRunsStreamingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRunsStreamingResponse' from JSON`,
  );
}
