/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ComputeTool = {
  /**
   * Setting this value to "compute" is mandatory to use the compute agent.
   */
  type: "compute";
};

/** @internal */
export type ComputeTool$Outbound = {
  type: "compute";
};

/** @internal */
export const ComputeTool$outboundSchema: z.ZodMiniType<
  ComputeTool$Outbound,
  ComputeTool
> = z.object({
  type: z.literal("compute"),
});

export function computeToolToJSON(computeTool: ComputeTool): string {
  return JSON.stringify(ComputeTool$outboundSchema.parse(computeTool));
}
