/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Setting this value to "compute" is mandatory to use the compute agent.
 */
export const ComputeToolType = {
  Compute: "compute",
} as const;
/**
 * Setting this value to "compute" is mandatory to use the compute agent.
 */
export type ComputeToolType = ClosedEnum<typeof ComputeToolType>;

export type ComputeTool = {
  /**
   * Setting this value to "compute" is mandatory to use the compute agent.
   */
  type: ComputeToolType;
};

/** @internal */
export const ComputeToolType$outboundSchema: z.ZodMiniEnum<
  typeof ComputeToolType
> = z.enum(ComputeToolType);

/** @internal */
export type ComputeTool$Outbound = {
  type: string;
};

/** @internal */
export const ComputeTool$outboundSchema: z.ZodMiniType<
  ComputeTool$Outbound,
  ComputeTool
> = z.object({
  type: ComputeToolType$outboundSchema,
});

export function computeToolToJSON(computeTool: ComputeTool): string {
  return JSON.stringify(ComputeTool$outboundSchema.parse(computeTool));
}
