/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * The format of the content to be returned.
 */
export const ContentsFormat = {
  Html: "html",
  Markdown: "markdown",
} as const;
/**
 * The format of the content to be returned.
 */
export type ContentsFormat = ClosedEnum<typeof ContentsFormat>;

/** @internal */
export const ContentsFormat$outboundSchema: z.ZodMiniEnum<
  typeof ContentsFormat
> = z.enum(ContentsFormat);
