/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Metadata about the web page. Only returned when 'metadata' is included in the formats array.
 */
export type ContentsMetadata = {
  /**
   * The OpenGraph site name of the web page.
   */
  siteName?: string | null | undefined;
  /**
   * The URL of the favicon of the web page's domain.
   */
  faviconUrl?: string | undefined;
};

/** @internal */
export const ContentsMetadata$inboundSchema: z.ZodMiniType<
  ContentsMetadata,
  unknown
> = z.pipe(
  z.object({
    site_name: z.optional(z.nullable(types.string())),
    favicon_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "site_name": "siteName",
      "favicon_url": "faviconUrl",
    });
  }),
);

export function contentsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<ContentsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentsMetadata' from JSON`,
  );
}
