/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ContentsFormats = {
  Html: "html",
  Markdown: "markdown",
  Metadata: "metadata",
} as const;
export type ContentsFormats = ClosedEnum<typeof ContentsFormats>;

/** @internal */
export const ContentsFormats$outboundSchema: z.ZodMiniEnum<
  typeof ContentsFormats
> = z.enum(ContentsFormats);
