/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Contents of the page if livecrawl was enabled.
 */
export type Contents = {
  /**
   * The HTML content of the page.
   */
  html?: string | undefined;
  /**
   * The Markdown content of the page.
   */
  markdown?: string | undefined;
};

/** @internal */
export const Contents$inboundSchema: z.ZodMiniType<Contents, unknown> = z
  .object({
    html: types.optional(types.string()),
    markdown: types.optional(types.string()),
  });

export function contentsFromJSON(
  jsonString: string,
): SafeParseResult<Contents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Contents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Contents' from JSON`,
  );
}
