/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * The country code that determines the geographical focus of the web results.
 */
export const Country = {
  Ar: "AR",
  Au: "AU",
  At: "AT",
  Be: "BE",
  Br: "BR",
  Ca: "CA",
  Cl: "CL",
  Dk: "DK",
  Fi: "FI",
  Fr: "FR",
  De: "DE",
  Hk: "HK",
  In: "IN",
  Id: "ID",
  It: "IT",
  Jp: "JP",
  Kr: "KR",
  My: "MY",
  Mx: "MX",
  Nl: "NL",
  Nz: "NZ",
  No: "NO",
  Cn: "CN",
  Pl: "PL",
  Pt: "PT",
  Ph: "PH",
  Ru: "RU",
  Sa: "SA",
  Za: "ZA",
  Es: "ES",
  Se: "SE",
  Ch: "CH",
  Tw: "TW",
  Tr: "TR",
  Gb: "GB",
  Us: "US",
} as const;
/**
 * The country code that determines the geographical focus of the web results.
 */
export type Country = ClosedEnum<typeof Country>;

/** @internal */
export const Country$outboundSchema: z.ZodMiniEnum<typeof Country> = z.enum(
  Country,
);
