/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CustomAgentRunsRequest = {
  /**
   * Set the value to a Custom Agent's ID. Learn how to obtain an agent ID here [Create Custom Agents](/agents/custom/create-agents).
   */
  agent: string;
  /**
   * The question you'd like to ask the agent
   */
  input: string;
  /**
   * Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished.
   */
  stream?: boolean | undefined;
};

/** @internal */
export type CustomAgentRunsRequest$Outbound = {
  agent: string;
  input: string;
  stream: boolean;
};

/** @internal */
export const CustomAgentRunsRequest$outboundSchema: z.ZodMiniType<
  CustomAgentRunsRequest$Outbound,
  CustomAgentRunsRequest
> = z.object({
  agent: z.string(),
  input: z.string(),
  stream: z._default(z.boolean(), false),
});

export function customAgentRunsRequestToJSON(
  customAgentRunsRequest: CustomAgentRunsRequest,
): string {
  return JSON.stringify(
    CustomAgentRunsRequest$outboundSchema.parse(customAgentRunsRequest),
  );
}
