/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  WebSearchTool,
  WebSearchTool$Outbound,
  WebSearchTool$outboundSchema,
} from "./websearchtool.js";

export type ExpressAgentRunsRequest = {
  /**
   * Setting this value to "express" is mandatory to use the express agent.
   */
  agent: "express";
  /**
   * The question you'd like to ask the agent
   */
  input: string;
  /**
   * Must be set to `true` when you want to stream the express agent response as it's being generated, and `false` when you want the response to return after the agent has finished.
   */
  stream?: boolean | undefined;
  /**
   * You can optionally ground the express agent response using results fetched from the web (max 1 web search)
   */
  tools?: Array<WebSearchTool> | undefined;
};

/** @internal */
export type ExpressAgentRunsRequest$Outbound = {
  agent: "express";
  input: string;
  stream: boolean;
  tools?: Array<WebSearchTool$Outbound> | undefined;
};

/** @internal */
export const ExpressAgentRunsRequest$outboundSchema: z.ZodMiniType<
  ExpressAgentRunsRequest$Outbound,
  ExpressAgentRunsRequest
> = z.object({
  agent: z.literal("express"),
  input: z.string(),
  stream: z._default(z.boolean(), false),
  tools: z.optional(z.array(WebSearchTool$outboundSchema)),
});

export function expressAgentRunsRequestToJSON(
  expressAgentRunsRequest: ExpressAgentRunsRequest,
): string {
  return JSON.stringify(
    ExpressAgentRunsRequest$outboundSchema.parse(expressAgentRunsRequest),
  );
}
