/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Setting this value to "express" is mandatory to use the express agent.
 */
export const ExpressAgentRunsRequestAgent = {
  Express: "express",
} as const;
/**
 * Setting this value to "express" is mandatory to use the express agent.
 */
export type ExpressAgentRunsRequestAgent = ClosedEnum<
  typeof ExpressAgentRunsRequestAgent
>;

/**
 * Setting this value to "web_search" is mandatory to use the web_search tool.
 */
export const ExpressAgentRunsRequestType = {
  WebSearch: "web_search",
} as const;
/**
 * Setting this value to "web_search" is mandatory to use the web_search tool.
 */
export type ExpressAgentRunsRequestType = ClosedEnum<
  typeof ExpressAgentRunsRequestType
>;

export type ExpressAgentRunsRequestTool = {
  /**
   * Setting this value to "web_search" is mandatory to use the web_search tool.
   */
  type: ExpressAgentRunsRequestType;
};

export type ExpressAgentRunsRequest = {
  /**
   * Setting this value to "express" is mandatory to use the express agent.
   */
  agent: ExpressAgentRunsRequestAgent;
  /**
   * The question you'd like to ask the agent
   */
  input: string;
  /**
   * Must be set to `true` when you want to stream the express agent response as it's being generated, and `false` when you want the response to return after the agent has finished.
   */
  stream?: boolean | undefined;
  /**
   * You can optionally ground the express agent response using results fetched from the web (max 1 web search)
   */
  tools?: Array<ExpressAgentRunsRequestTool> | undefined;
};

/** @internal */
export const ExpressAgentRunsRequestAgent$outboundSchema: z.ZodMiniEnum<
  typeof ExpressAgentRunsRequestAgent
> = z.enum(ExpressAgentRunsRequestAgent);

/** @internal */
export const ExpressAgentRunsRequestType$outboundSchema: z.ZodMiniEnum<
  typeof ExpressAgentRunsRequestType
> = z.enum(ExpressAgentRunsRequestType);

/** @internal */
export type ExpressAgentRunsRequestTool$Outbound = {
  type: string;
};

/** @internal */
export const ExpressAgentRunsRequestTool$outboundSchema: z.ZodMiniType<
  ExpressAgentRunsRequestTool$Outbound,
  ExpressAgentRunsRequestTool
> = z.object({
  type: ExpressAgentRunsRequestType$outboundSchema,
});

export function expressAgentRunsRequestToolToJSON(
  expressAgentRunsRequestTool: ExpressAgentRunsRequestTool,
): string {
  return JSON.stringify(
    ExpressAgentRunsRequestTool$outboundSchema.parse(
      expressAgentRunsRequestTool,
    ),
  );
}

/** @internal */
export type ExpressAgentRunsRequest$Outbound = {
  agent: string;
  input: string;
  stream: boolean;
  tools?: Array<ExpressAgentRunsRequestTool$Outbound> | undefined;
};

/** @internal */
export const ExpressAgentRunsRequest$outboundSchema: z.ZodMiniType<
  ExpressAgentRunsRequest$Outbound,
  ExpressAgentRunsRequest
> = z.object({
  agent: ExpressAgentRunsRequestAgent$outboundSchema,
  input: z.string(),
  stream: z._default(z.boolean(), false),
  tools: z.optional(
    z.array(z.lazy(() => ExpressAgentRunsRequestTool$outboundSchema)),
  ),
});

export function expressAgentRunsRequestToJSON(
  expressAgentRunsRequest: ExpressAgentRunsRequest,
): string {
  return JSON.stringify(
    ExpressAgentRunsRequest$outboundSchema.parse(expressAgentRunsRequest),
  );
}
