/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Specifies the freshness of the results to return.
 */
export const Freshness = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
/**
 * Specifies the freshness of the results to return.
 */
export type Freshness = ClosedEnum<typeof Freshness>;

/** @internal */
export const Freshness$outboundSchema: z.ZodMiniEnum<typeof Freshness> = z.enum(
  Freshness,
);
