/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Language = {
  Ar: "AR",
  Eu: "EU",
  Bn: "BN",
  Bg: "BG",
  Ca: "CA",
  ZhHans: "ZH-HANS",
  ZhHant: "ZH-HANT",
  Hr: "HR",
  Cs: "CS",
  Da: "DA",
  Nl: "NL",
  En: "EN",
  EnGb: "EN-GB",
  Et: "ET",
  Fi: "FI",
  Fr: "FR",
  Gl: "GL",
  De: "DE",
  El: "EL",
  Gu: "GU",
  He: "HE",
  Hi: "HI",
  Hu: "HU",
  Is: "IS",
  It: "IT",
  Jp: "JP",
  Kn: "KN",
  Ko: "KO",
  Lv: "LV",
  Lt: "LT",
  Ms: "MS",
  Ml: "ML",
  Mr: "MR",
  Nb: "NB",
  Pl: "PL",
  PtBr: "PT-BR",
  PtPt: "PT-PT",
  Pa: "PA",
  Ro: "RO",
  Ru: "RU",
  Sr: "SR",
  Sk: "SK",
  Sl: "SL",
  Es: "ES",
  Sv: "SV",
  Ta: "TA",
  Te: "TE",
  Th: "TH",
  Tr: "TR",
  Uk: "UK",
  Vi: "VI",
} as const;
export type Language = ClosedEnum<typeof Language>;

/** @internal */
export const Language$outboundSchema: z.ZodMiniEnum<typeof Language> = z.enum(
  Language,
);
