/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Indicates the format of the livecrawled content.
 */
export const LiveCrawlFormats = {
  Html: "html",
  Markdown: "markdown",
} as const;
/**
 * Indicates the format of the livecrawled content.
 */
export type LiveCrawlFormats = ClosedEnum<typeof LiveCrawlFormats>;

/** @internal */
export const LiveCrawlFormats$outboundSchema: z.ZodMiniEnum<
  typeof LiveCrawlFormats
> = z.enum(LiveCrawlFormats);
