/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Indicates which section(s) of search results to livecrawl and return full page content.
 */
export const LiveCrawl = {
  Web: "web",
  News: "news",
  All: "all",
} as const;
/**
 * Indicates which section(s) of search results to livecrawl and return full page content.
 */
export type LiveCrawl = ClosedEnum<typeof LiveCrawl>;

/** @internal */
export const LiveCrawl$outboundSchema: z.ZodMiniEnum<typeof LiveCrawl> = z.enum(
  LiveCrawl,
);
