/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Select whether to receive a medium or high length model response.
 */
export const ReportVerbosity = {
  Medium: "medium",
  High: "high",
} as const;
/**
 * Select whether to receive a medium or high length model response.
 */
export type ReportVerbosity = ClosedEnum<typeof ReportVerbosity>;

/** @internal */
export const ReportVerbosity$outboundSchema: z.ZodMiniEnum<
  typeof ReportVerbosity
> = z.enum(ReportVerbosity);
