/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ReportVerbosity,
  ReportVerbosity$outboundSchema,
} from "./reportverbosity.js";
import { SearchEffort, SearchEffort$outboundSchema } from "./searcheffort.js";

export type ResearchTool = {
  /**
   * Setting this value to "research" is mandatory to use the research agent.
   */
  type: "research";
  /**
   * This parameter maps to different configurations regarding the depth of research the tool can perform. Its values range from `low`, `medium` to `high`.
   *
   * @remarks
   *
   * Alternatively, use `auto` mode for a more dynamic search approach, allowing the tool the freedom to adjust its subparameters.
   */
  searchEffort: SearchEffort;
  /**
   * Select whether to receive a medium or high length model response.
   */
  reportVerbosity: ReportVerbosity;
};

/** @internal */
export type ResearchTool$Outbound = {
  type: "research";
  search_effort: string;
  report_verbosity: string;
};

/** @internal */
export const ResearchTool$outboundSchema: z.ZodMiniType<
  ResearchTool$Outbound,
  ResearchTool
> = z.pipe(
  z.object({
    type: z.literal("research"),
    searchEffort: SearchEffort$outboundSchema,
    reportVerbosity: ReportVerbosity$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      searchEffort: "search_effort",
      reportVerbosity: "report_verbosity",
    });
  }),
);

export function researchToolToJSON(researchTool: ResearchTool): string {
  return JSON.stringify(ResearchTool$outboundSchema.parse(researchTool));
}
