/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseDoneType = {
  ResponseDone: "response.done",
} as const;
export type ResponseDoneType = ClosedEnum<typeof ResponseDoneType>;

export type ResponseDoneResponse = {
  /**
   * Total runtime in milliseconds
   */
  runTimeMs: string;
  /**
   * Whether the response is complete
   */
  finished: boolean;
};

export type ResponseDone = {
  seqId: number;
  type: ResponseDoneType;
  response: ResponseDoneResponse;
};

/** @internal */
export const ResponseDoneType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseDoneType
> = z.enum(ResponseDoneType);

/** @internal */
export const ResponseDoneResponse$inboundSchema: z.ZodMiniType<
  ResponseDoneResponse,
  unknown
> = z.pipe(
  z.object({
    run_time_ms: types.string(),
    finished: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "run_time_ms": "runTimeMs",
    });
  }),
);

export function responseDoneResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseDoneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseDoneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseDoneResponse' from JSON`,
  );
}

/** @internal */
export const ResponseDone$inboundSchema: z.ZodMiniType<ResponseDone, unknown> =
  z.pipe(
    z.object({
      seq_id: types.number(),
      type: ResponseDoneType$inboundSchema,
      response: z.lazy(() => ResponseDoneResponse$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "seq_id": "seqId",
      });
    }),
  );

export function responseDoneFromJSON(
  jsonString: string,
): SafeParseResult<ResponseDone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseDone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseDone' from JSON`,
  );
}
