/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseOutputTextDeltaType = {
  ResponseOutputTextDelta: "response.output_text.delta",
} as const;
export type ResponseOutputTextDeltaType = ClosedEnum<
  typeof ResponseOutputTextDeltaType
>;

export const TypeMessageAnswer = {
  MessageAnswer: "message.answer",
} as const;
export type TypeMessageAnswer = ClosedEnum<typeof TypeMessageAnswer>;

export type ResponseOutputTextDeltaResponse = {
  outputIndex: number;
  type: TypeMessageAnswer;
  /**
   * Incremental text content
   */
  delta: string;
};

export type ResponseOutputTextDelta = {
  seqId: number;
  type: ResponseOutputTextDeltaType;
  response: ResponseOutputTextDeltaResponse;
};

/** @internal */
export const ResponseOutputTextDeltaType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseOutputTextDeltaType
> = z.enum(ResponseOutputTextDeltaType);

/** @internal */
export const TypeMessageAnswer$inboundSchema: z.ZodMiniEnum<
  typeof TypeMessageAnswer
> = z.enum(TypeMessageAnswer);

/** @internal */
export const ResponseOutputTextDeltaResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputTextDeltaResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
    type: TypeMessageAnswer$inboundSchema,
    delta: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputTextDeltaResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputTextDeltaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputTextDeltaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputTextDeltaResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputTextDelta$inboundSchema: z.ZodMiniType<
  ResponseOutputTextDelta,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: ResponseOutputTextDeltaType$inboundSchema,
    response: z.lazy(() => ResponseOutputTextDeltaResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputTextDeltaFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputTextDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputTextDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputTextDelta' from JSON`,
  );
}
