/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseOutputItemDoneType = {
  ResponseOutputItemDone: "response.output_item.done",
} as const;
export type ResponseOutputItemDoneType = ClosedEnum<
  typeof ResponseOutputItemDoneType
>;

export type ResponseOutputItemDoneResponse = {
  outputIndex: number;
};

export type ResponseOutputItemDone = {
  seqId: number;
  type: ResponseOutputItemDoneType;
  response: ResponseOutputItemDoneResponse;
};

/** @internal */
export const ResponseOutputItemDoneType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseOutputItemDoneType
> = z.enum(ResponseOutputItemDoneType);

/** @internal */
export const ResponseOutputItemDoneResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputItemDoneResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputItemDoneResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputItemDoneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputItemDoneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputItemDoneResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputItemDone$inboundSchema: z.ZodMiniType<
  ResponseOutputItemDone,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: ResponseOutputItemDoneType$inboundSchema,
    response: z.lazy(() => ResponseOutputItemDoneResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputItemDoneFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputItemDone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputItemDone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputItemDone' from JSON`,
  );
}
