/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentRunsResponseWebSearchResult,
  AgentRunsResponseWebSearchResult$inboundSchema,
} from "./agentrunsresponsewebsearchresult.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseOutputContentFullType = {
  ResponseOutputContentFull: "response.output_content.full",
} as const;
export type ResponseOutputContentFullType = ClosedEnum<
  typeof ResponseOutputContentFullType
>;

export const TypeWebSearchResults = {
  WebSearchResults: "web_search.results",
} as const;
export type TypeWebSearchResults = ClosedEnum<typeof TypeWebSearchResults>;

export type ResponseOutputContentFullResponse = {
  outputIndex: number;
  type: TypeWebSearchResults;
  /**
   * Complete web search results
   */
  full: Array<AgentRunsResponseWebSearchResult>;
};

export type ResponseOutputContentFull = {
  seqId: number;
  type: ResponseOutputContentFullType;
  response: ResponseOutputContentFullResponse;
};

/** @internal */
export const ResponseOutputContentFullType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseOutputContentFullType
> = z.enum(ResponseOutputContentFullType);

/** @internal */
export const TypeWebSearchResults$inboundSchema: z.ZodMiniEnum<
  typeof TypeWebSearchResults
> = z.enum(TypeWebSearchResults);

/** @internal */
export const ResponseOutputContentFullResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputContentFullResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
    type: TypeWebSearchResults$inboundSchema,
    full: z.array(AgentRunsResponseWebSearchResult$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputContentFullResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputContentFullResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputContentFullResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputContentFullResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputContentFull$inboundSchema: z.ZodMiniType<
  ResponseOutputContentFull,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: ResponseOutputContentFullType$inboundSchema,
    response: z.lazy(() => ResponseOutputContentFullResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputContentFullFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputContentFull, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputContentFull$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputContentFull' from JSON`,
  );
}
