/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ResponseOutputTextDeltaResponse = {
  outputIndex: number;
  type: "message.answer";
  /**
   * Incremental text content
   */
  delta: string;
};

export type ResponseOutputTextDelta = {
  seqId: number;
  type: "response.output_text.delta";
  response: ResponseOutputTextDeltaResponse;
};

/** @internal */
export const ResponseOutputTextDeltaResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputTextDeltaResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
    type: types.literal("message.answer"),
    delta: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputTextDeltaResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputTextDeltaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputTextDeltaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputTextDeltaResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputTextDelta$inboundSchema: z.ZodMiniType<
  ResponseOutputTextDelta,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: types.literal("response.output_text.delta"),
    response: z.lazy(() => ResponseOutputTextDeltaResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputTextDeltaFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputTextDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputTextDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputTextDelta' from JSON`,
  );
}
