/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * SSE event signifying the response stream has been created
 */
export type ResponseCreated = {
  seqId: number;
  type: "response.created";
};

/** @internal */
export const ResponseCreated$inboundSchema: z.ZodMiniType<
  ResponseCreated,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: types.literal("response.created"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseCreatedFromJSON(
  jsonString: string,
): SafeParseResult<ResponseCreated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseCreated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseCreated' from JSON`,
  );
}
