/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentRunsResponseWebSearchResult,
  AgentRunsResponseWebSearchResult$inboundSchema,
} from "./agentrunsresponsewebsearchresult.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ResponseOutputContentFullResponse = {
  outputIndex: number;
  type: "web_search.results";
  /**
   * Complete web search results
   */
  full: Array<AgentRunsResponseWebSearchResult>;
};

export type ResponseOutputContentFull = {
  seqId: number;
  type: "response.output_content.full";
  response: ResponseOutputContentFullResponse;
};

/** @internal */
export const ResponseOutputContentFullResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputContentFullResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
    type: types.literal("web_search.results"),
    full: z.array(AgentRunsResponseWebSearchResult$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputContentFullResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputContentFullResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputContentFullResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputContentFullResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputContentFull$inboundSchema: z.ZodMiniType<
  ResponseOutputContentFull,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: types.literal("response.output_content.full"),
    response: z.lazy(() => ResponseOutputContentFullResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputContentFullFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputContentFull, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputContentFull$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputContentFull' from JSON`,
  );
}
