/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseOutputItemAddedType = {
  ResponseOutputItemAdded: "response.output_item.added",
} as const;
export type ResponseOutputItemAddedType = ClosedEnum<
  typeof ResponseOutputItemAddedType
>;

export type ResponseOutputItemAddedResponse = {
  /**
   * The index of the output item in the response
   */
  outputIndex: number;
};

/**
 * SSE event signifying an output item has been added
 */
export type ResponseOutputItemAdded = {
  seqId: number;
  type: ResponseOutputItemAddedType;
  response: ResponseOutputItemAddedResponse;
};

/** @internal */
export const ResponseOutputItemAddedType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseOutputItemAddedType
> = z.enum(ResponseOutputItemAddedType);

/** @internal */
export const ResponseOutputItemAddedResponse$inboundSchema: z.ZodMiniType<
  ResponseOutputItemAddedResponse,
  unknown
> = z.pipe(
  z.object({
    output_index: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_index": "outputIndex",
    });
  }),
);

export function responseOutputItemAddedResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputItemAddedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputItemAddedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputItemAddedResponse' from JSON`,
  );
}

/** @internal */
export const ResponseOutputItemAdded$inboundSchema: z.ZodMiniType<
  ResponseOutputItemAdded,
  unknown
> = z.pipe(
  z.object({
    seq_id: types.number(),
    type: ResponseOutputItemAddedType$inboundSchema,
    response: z.lazy(() => ResponseOutputItemAddedResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "seq_id": "seqId",
    });
  }),
);

export function responseOutputItemAddedFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputItemAdded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputItemAdded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputItemAdded' from JSON`,
  );
}
