/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not.
 */
export const SafeSearch = {
  Off: "off",
  Moderate: "moderate",
  Strict: "strict",
} as const;
/**
 * Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not.
 */
export type SafeSearch = ClosedEnum<typeof SafeSearch>;

/** @internal */
export const SafeSearch$outboundSchema: z.ZodMiniEnum<typeof SafeSearch> = z
  .enum(SafeSearch);
