/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * This parameter maps to different configurations regarding the depth of research the tool can perform. Its values range from `low`, `medium` to `high`.
 *
 * @remarks
 *
 * Alternatively, use `auto` mode for a more dynamic search approach, allowing the tool the freedom to adjust its subparameters.
 */
export const SearchEffort = {
  Auto: "auto",
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
/**
 * This parameter maps to different configurations regarding the depth of research the tool can perform. Its values range from `low`, `medium` to `high`.
 *
 * @remarks
 *
 * Alternatively, use `auto` mode for a more dynamic search approach, allowing the tool the freedom to adjust its subparameters.
 */
export type SearchEffort = ClosedEnum<typeof SearchEffort>;

/** @internal */
export const SearchEffort$outboundSchema: z.ZodMiniEnum<typeof SearchEffort> = z
  .enum(SearchEffort);
