/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Controls the level of detail provided by the agent's response. Choosing high maps to a long-form report while medium maps to a medium verbosity report that captures most details but is less comprehensive.
 */
export const Verbosity = {
  Medium: "medium",
  High: "high",
} as const;
/**
 * Controls the level of detail provided by the agent's response. Choosing high maps to a long-form report while medium maps to a medium verbosity report that captures most details but is less comprehensive.
 */
export type Verbosity = ClosedEnum<typeof Verbosity>;

/** @internal */
export const Verbosity$outboundSchema: z.ZodMiniEnum<typeof Verbosity> = z.enum(
  Verbosity,
);
