/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WebSearchTool = {
  /**
   * Setting this value to "web_search" is mandatory to use the web_search tool.
   */
  type: "web_search";
};

/** @internal */
export type WebSearchTool$Outbound = {
  type: "web_search";
};

/** @internal */
export const WebSearchTool$outboundSchema: z.ZodMiniType<
  WebSearchTool$Outbound,
  WebSearchTool
> = z.object({
  type: z.literal("web_search"),
});

export function webSearchToolToJSON(webSearchTool: WebSearchTool): string {
  return JSON.stringify(WebSearchTool$outboundSchema.parse(webSearchTool));
}
